import axios from 'axios'
const api = axios.create({ baseURL:'/api' })
api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c})
api.interceptors.response.use(r=>r,e=>{if(e.response?.status===401){localStorage.removeItem('token');window.location.href='/login'}return Promise.reject(e)})
export default api
export const login=(email:string,password:string)=>api.post('/auth/login',new URLSearchParams({username:email,password}))
export const register=(email:string,password:string,full_name:string)=>api.post('/auth/register',{email,password,full_name})
export const getMe=()=>api.get('/auth/me')
export const getAccounts=()=>api.get('/accounts/')
export const getNetWorth=()=>api.get('/accounts/net-worth')
export const createAccount=(d:object)=>api.post('/accounts/',d)
export const deleteAccount=(id:number)=>api.delete(`/accounts/${id}`)
export const getTransactions=(p?:object)=>api.get('/transactions/',{params:p})
export const createTransaction=(d:object)=>api.post('/transactions/',d)
export const deleteTransaction=(id:number)=>api.delete(`/transactions/${id}`)
export const getMonthlySummary=(year:number,month:number)=>api.get('/transactions/summary',{params:{year,month}})
export const getSpendingByCat=(year:number,month:number)=>api.get('/transactions/spending-by-category',{params:{year,month}})
export const getBudgets=(year:number,month:number)=>api.get('/budgets/',{params:{year,month}})
export const createBudget=(d:object)=>api.post('/budgets/',d)
export const deleteBudget=(id:number)=>api.delete(`/budgets/${id}`)
export const getGoals=()=>api.get('/goals/')
export const createGoal=(d:object)=>api.post('/goals/',d)
export const updateGoal=(id:number,d:object)=>api.patch(`/goals/${id}`,d)
export const deleteGoal=(id:number)=>api.delete(`/goals/${id}`)
export const getCategories=()=>api.get('/categories/')
export const getInsights=()=>api.get('/ai/insights')
export const sendChat=(messages:object[])=>api.post('/ai/chat',{messages})
